# Site settings
title:       learningswift
email:       learnswift@yahoo.com 
author:      Rohit G.
description: "Let's learn swift together and create amazing apps!"
baseurl:     "/learningswift/tutorial"
url:         "https://github.com/learningswift/tutorial"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
